---
title: "strings and factors"
author: "zy"
date: "10/21/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
library(p8105.datasets)
```


```{r}
string_vec=c("my","name","is","Jeff")
str_detect(string_vec, "jeff")
```



```{r}
string_vec=c(
  "I think we all rule for participating",
  "I think I have been caught",
  "I think this will be quite fun actually",
  "it will be fun, i think"
)
str_detect(string_vec, "^i think")

```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )
str_detect(string_vec,"[0-9][a-zA-Z]")
```

```{r}
str_detect(string_vec,"711")
```

```{r}
string_vec=c(
  'The CI is [2,5]',
  ':-]',
  ':-[',
  'I foung the answer on pages[6-7]'
  )

str_detect(string_vec,"\\[")
```
```{r}
factor_vec=factor(c("male","male","female","female"))

as.numeric(factor_vec)

fct_relevel(factor_vec,"male")
as.numeric(factor_vec)
```

```{r}
nsduh_url="http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj=
  read_html(nsduh_url)%>%
  html_table()%>%
  first()%>%
  slice(-1)
table_marj

```

```{r}
marj_df=
  table_marj%>%
  select(-contains("P value"))%>%
  pivot_longer(
    -State,
    names_to="age_year",
    values_to="percent")%>%
  separate(age_year,into=c("age","year"),"\\(")%>%
  mutate(
    year=str_replace(year,"\\(",""),
    precent=str_replace(percent,"[a-c]$",""),
    percent=as.numeric(percent)
  )%>%
  filter(!State%in%c("Total U.S.","Northeast","Mideast","South","West"))

```

```{r}
marj_df%>%
  filter(age=="12-17")%>%
  mutate(State=fct_reorder(State,percent))%>%
  ggplot(aes(x=State,y=percent,color=year))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r}
data("rest_inspec")
```

```{r}
rest_inspec%>%
  janitor::tabyl(boro,grade)
```

```{r}
rest_inspec=
  rest_inspec%>%
  filter(
    str_detect(grade,"[ABC]"),
    !(boro=="Missing"))%>%
  mutate(boro=str_to_title(boro))
```

```{r}
rest_inspec%>%
  filter(str_detect(dba,"[Pp][Ii][Zz][Zz][Aa]"))%>%
  mutate(
    boro=fct_infreq(boro),
    boro=fct_recode(boro,"The City"="Manhattan")
  )%>%
  ggplot(aes(x=boro,fill=grade))+
  geom_bar()
  
```



